# Generated by Django 5.0.4 on 2024-04-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Lecturer'), (3, 'User')], default=1),
        ),
    ]
