# Generated by Django 5.0.4 on 2024-06-10 09:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0005_remove_outline_image_outline_up_file_subject_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dvzsftuep/image/upload/v1718008117/e83yxveneoxzwh4ehfvu.png', max_length=255),
        ),
    ]
