# Generated by Django 5.0.4 on 2024-06-15 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0007_subject_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='updated_date',
        ),
    ]
