# Generated by Django 5.0.4 on 2024-06-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0009_course_active_course_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
