# Generated by Django 5.0.4 on 2024-06-15 11:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0010_alter_course_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='up_file',
            field=cloudinary.models.CloudinaryField(default=None, max_length=255),
        ),
    ]
