# Generated by Django 5.0.4 on 2024-06-15 13:19

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appapi', '0011_alter_outline_up_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outline',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
